name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          zip unzip tar \
          openjdk-17-jdk \
          python3-pip \
          libffi-dev \
          libssl-dev \
          build-essential \
          libsqlite3-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libreadline-dev \
          libgdbm-dev \
          libbz2-dev \
          liblzma-dev \
          zlib1g-dev \
          libblas-dev \
          liblapack-dev \
          libatlas-base-dev \
          libjpeg-dev \
          libfreetype6-dev \
          pkg-config \
          git

        pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Initialize Buildozer
      run: |
        buildozer init

    - name: First Build to Trigger SDK Download
      run: |
        buildozer android clean
        buildozer android update

    - name: Accept SDK Licenses
      run: |
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Final Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-APK
        path: bin/*.apk
